---
exclude_paths:
  - "**/main.go"
  - "**_test.go"
  - "README.md"
  - "proto/**"
  - "**/**.md"
  - "scripts/experiments/**"
  - "**/mocks/*.go"
  - "**/app/app.go"
  - "scripts/mongo/**"
  - "**/**.yaml"
  - "**/**.yml"
  - "infrastructure/**"
  - "pkg/testcontainers/**"