#version: '3.8'
#
#services:
#  hello-world:
#    build: .
#    container_name: hello-world-container
#    command: ["./hello-world"]

version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
