name: Codacy Coverage Reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    name: codacy-coverage-reporter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Run tests, generate coverage, upload to codacy
        run: |
          go test ./... -coverprofile coverage.out
          go tool cover -func coverage.out
          curl -Ls https://coverage.codacy.com/get.sh | bash -s report --partial --force-coverage-parser go -r coverage.out
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}